version: "3"
services:
  hms-jenkins:
    container_name: hms-jenkins
    image: jenkinsci/blueocean:1.22.0-bcc31d32159f
    restart: always
    environment:
      - CHROME_BIN:/usr/bin/google-chrome
      # - BUILD_ID:1
    user: root
    # passwd: tcuser
    privileged: true
    # net: host
    ports:
      - 8081:8080
    volumes:
      - ./app:/app/hms-sdk-widget
      - ./fake:/app/hms-fake-data
      # - ./fake:/var/jenkins_home/workspace/hms-jenkins_live/fake
      - /var/lib/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  hms-sdk-widget:
    container_name: hms-sdk-widget
    environment:
      - DCP_PORT=3000
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env.live
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./app:/app/hms-sdk-widget
      - /app/hms-sdk-widget/node_modules # [*] Need to refer to node_modules in container of the app
    entrypoint:
      - sh
      - entrypoint-live.sh
    restart: always

  hms-fake-data:
    container_name: hms-fake-data
    environment:
      - FAKE_PORT=3002
    build:
      context: ./fake
      dockerfile: Dockerfile
    env_file:
      - ./fake/.env.development
    ports:
      - "3002:3002"
    expose:
      - 3002
    volumes:
      - ./fake:/app/hms-fake-data
      - /app/hms-fake-data/node_modules # [*] Need to refer to node_modules in container of the app
    entrypoint:
      - sh
      - entrypoint-dev.sh
    restart: always

networks:
  default:
    external:
      name: iassdk
